//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AZE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; ist not recognized. Valid Parameters are:
        ///&quot;begin&quot;: begin attendance
        ///&quot;end&quot;: end attendance.
        /// </summary>
        public static string ConsoleHelp {
            get {
                return ResourceManager.GetString("ConsoleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work attendance.
        /// </summary>
        public static string GroupBoxHeaderAttendance {
            get {
                return ResourceManager.GetString("GroupBoxHeaderAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string LabelBegin {
            get {
                return ResourceManager.GetString("LabelBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string LabelEnd {
            get {
                return ResourceManager.GetString("LabelEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string LabelNetWork {
            get {
                return ResourceManager.GetString("LabelNetWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string LabelPause {
            get {
                return ResourceManager.GetString("LabelPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string LabelRow {
            get {
                return ResourceManager.GetString("LabelRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value was already set. Overwrite value?.
        /// </summary>
        public static string MessageTextConfirm {
            get {
                return ResourceManager.GetString("MessageTextConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure?.
        /// </summary>
        public static string MessageTitleConfirm {
            get {
                return ResourceManager.GetString("MessageTitleConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string TextBeginButton {
            get {
                return ResourceManager.GetString("TextBeginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string TextEndButton {
            get {
                return ResourceManager.GetString("TextEndButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string TextMinutes {
            get {
                return ResourceManager.GetString("TextMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string TextPauseButton {
            get {
                return ResourceManager.GetString("TextPauseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set attendance begin.
        /// </summary>
        public static string ToolTipBeginButton {
            get {
                return ResourceManager.GetString("ToolTipBeginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current timesheet values for today.
        /// </summary>
        public static string ToolTipCurrentValues {
            get {
                return ResourceManager.GetString("ToolTipCurrentValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set attendance end.
        /// </summary>
        public static string ToolTipEndButton {
            get {
                return ResourceManager.GetString("ToolTipEndButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or subtract pause duration.
        /// </summary>
        public static string ToolTipPauseButton {
            get {
                return ResourceManager.GetString("ToolTipPauseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive and negative values are allowed.
        /// </summary>
        public static string ToolTipPauseUpDown {
            get {
                return ResourceManager.GetString("ToolTipPauseUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select current time table sheet.
        /// </summary>
        public static string ToolTipSelectFile {
            get {
                return ResourceManager.GetString("ToolTipSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AZE attendance clock.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
